// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  angular.module('weeeeApp').controller('MainCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Testacular'];
  });

}).call(this);
